name: Deploy-Android-TEST 

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
    
env:
  APP_CENTER_TOKEN: $  
  APP_NAME: $MyApp-Android/ENV_TEST  
  TESTING_GROUP: $ENV_TEST 
  UPLOAD_FILE: $android/app/build/outputs/apk/app-release.apk  
  

jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Example variable usage
        run: git tag ${{ github.event.inputs.version }}
        
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: yarn

      - name: Build android
        run: yarn android:release

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: $
          token: $
          group: $
          file: $
          notifyTesters: true
          debug: false
